# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgsema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radnik',
            name='administracija',
        ),
        migrations.RemoveField(
            model_name='radnik',
            name='izvestaji',
        ),
    ]
