# Generated by Django 4.1.7 on 2023-02-28 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgsema', '0002_auto_20170216_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drzava',
            name='valuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orgsema.valuta', verbose_name='valuta'),
        ),
        migrations.AlterField(
            model_name='orgjed',
            name='mesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orgsema.naseljenomesto', verbose_name='mesto'),
        ),
        migrations.AlterField(
            model_name='radnik',
            name='uloga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orgsema.uloga', verbose_name='uloga'),
        ),
        migrations.AlterField(
            model_name='radnik',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
