# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osnovni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muzejskipredmet',
            name='br_primeraka',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='broj primeraka'),
        ),
    ]
