# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import osnovni.models


class Migration(migrations.Migration):

    dependencies = [
        ('osnovni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muzejskipredmet',
            name='fotografija',
            field=models.FileField(blank=True, null=True, upload_to=osnovni.models.get_path_fotografija, verbose_name='fotografija'),
        ),
    ]
