# Generated by Django 4.1.7 on 2023-02-28 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgsema', '0003_alter_drzava_valuta_alter_orgjed_mesto_and_more'),
        ('osnovni', '0002_auto_20170216_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istorijaizmenapredmeta',
            name='radnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orgsema.radnik', verbose_name='radnik'),
        ),
        migrations.AlterField(
            model_name='muzejskipredmet',
            name='datum_kreiranja',
            field=models.DateField(verbose_name='datum unosa'),
        ),
        migrations.AlterField(
            model_name='muzejskipredmet',
            name='kategorija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='osnovni.kategorijapredmeta', verbose_name='kategorija'),
        ),
        migrations.AlterField(
            model_name='muzejskipredmet',
            name='kreirao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orgsema.radnik', verbose_name='zapis uneo'),
        ),
        migrations.AlterField(
            model_name='muzejskipredmet',
            name='literatura',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='literatura o predmet'),
        ),
        migrations.AlterField(
            model_name='muzejskipredmet',
            name='mesto_nastanka2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orgsema.naseljenomesto', verbose_name='mesto nastanka'),
        ),
        migrations.AlterField(
            model_name='muzejskipredmet',
            name='nacin_nabavke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='osnovni.nacinnabavke', verbose_name='način nabavke'),
        ),
        migrations.AlterField(
            model_name='muzejskipredmet',
            name='vrsta_predmeta',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='predmet'),
        ),
        migrations.AlterField(
            model_name='muzejskipredmet',
            name='vrsta_zbirke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='osnovni.vrstazbirke', verbose_name='vrsta zbirke'),
        ),
    ]
